version: '3.9'


services:
  admin:
    container_name: nestjs-nats-admin
    build: ./backend/admin
    restart: always
    ports:
      - "3001:3001"
      
    volumes:
      - ./backend/admin:/app/backend/admin
    network_mode: aph-network
  aph:
    container_name: nestjs-nats-aph
    build: ./backend/aph
    volumes:
      - ./backend/aph:/app/backend/aph
    ports:
      - "3000:3000"
    network_mode: aph-network
    
    


