export default[
    "Blanco",
    "Silver",
    "Transparente",
    "Negro",
    "Plata",
    "Gris+blanco",
    "Verde Manzana",
    "Gris + Negro",
    "Blanco + Negro",
    "Rojo - Rosado",
    "Madera",
    "GRIS OSCURO/NEGRO",
    "Royal Blue",
    "Cartón",
    "Negro+Plata",
    "Madera Bamboo",
    "Amarilla",
    "Bambú",
    "Azul rey",
    "Natural",  
    "Rojo",
    "Azul",
    "Verde",
    "Amarillo",
    "Naranja",
    "Gris",
    "Rosado",
    "Morado",
    "Marrón",
    "Beige",
    "Celeste",
    "Turquesa",
    "Dorado",
    "Plateado",
    "Crema",
    "Café",
    "Lila",
    "Violeta",
    "Fucsia",
    "Carmesí",
    "Índigo",
    "Grisáceo",
    "Verde oscuro",
    "Magenta",
    "Mostaza",
    "Oliva",
    "Salmon",
    "Amarillo pálido",
    "Cian",
    "Amarillo claro",
    "Azul claro",
    "Amarillo verdoso",
    "Gris oscuro",
    "Gris Oscuro",
    "Verde oliva",
    "Verde claro",
    "Rojo oscuro",
    "Azul marino",
    "Naranja oscuro",
    "Azul verdoso",
    "Verde menta",
    "Turquesa oscuro",
    "Verde oscuro",
    "Marrón claro",
    "Gris claro",
    "Azul oscuro",
    "Azul cielo",
    "Vino",
    "Rosa claro",
    "Rosa oscuro",
    "Verde agua",
    "Azul petróleo",
    "Beige claro",
    "Terracota",
    "Verde lima",
    "Azul celeste",
    "Verde musgo",
    "Rosa",
    "Verde esmeralda",
    "Azul eléctrico",
    "Azul Osc.",
    "Amarilla",
    "Gris Hasped",
    "Verde cali",
    "Surtido",
    "Khaki claro",
    "Base transparente",
    "Negra",
    "Verde limon",
    "Bamboo",
    "Blanca",
    "Roja",
    "Blanco Crema",
    "Khaki",
    "Blanco Transparente",
    "Verde Trigo",
    "Rojo Trigo",
    "Azul Trigo",
    "Trigo",
    "Fucsia",
    "Tricolor",
    "Azul Marino",
    "Gris Jaspel",
    "Verde Lima",
    "Ceniza",
    "Royal",
    "Rojo Cardenal",
    "Morado",
    "Rosado Azalea",
    "Verde Claro",
    "Azul Rey Mate",
    "Azul Rey Frost",
    "Blanco Mate",
    "Naranja",
    


  ]