export default[
    "Blanco",
    "Negro",
    "Rojo",
    "Azul",
    "Verde",
    "Amarillo",
    "Naranja",
    "Gris",
    "Rosado",
    "Morado",
    "Marrón",
    "Beige",
    "Celeste",
    "Turquesa",
    "Dorado",
    "Plateado",
    "Crema",
    "Café",
    "Lila",
    "Violeta",
    "Fucsia",
    "Carmesí",
    "Índigo",
    "Grisáceo",
    "Verde oscuro",
    "Magenta",
    "Mostaza",
    "Oliva",
    "Salmon",
    "Amarillo pálido",
    "Cian",
    "Amarillo claro",
    "Azul claro",
    "Amarillo verdoso",
    "Gris oscuro",
    "Verde oliva",
    "Verde claro",
    "Rojo oscuro",
    "Azul marino",
    "Naranja oscuro",
    "Azul verdoso",
    "Verde menta",
    "Turquesa oscuro",
    "Verde oscuro",
    "Marrón claro",
    "Gris claro",
    "Azul oscuro",
    "Azul cielo",
    "Vino",
    "Rosa claro",
    "Rosa oscuro",
    "Verde agua",
    "Azul petróleo",
    "Beige claro",
    "Terracota",
    "Verde lima",
    "Azul celeste",
    "Verde musgo",
    "Rosa",
    "Verde esmeralda",
    "Azul eléctrico",

  ]